EVENT_REMINDER_1HR_BEFORE = "event_reminder_1hr_before"
EVENT_REMINDER_5MINS_BEFORE = "event_reminder_5mins_before"
COMMS_TO_EVENT_MAP = {
    EVENT_REMINDER_1HR_BEFORE: "HQ793PHHYJMNFSJXJQFYAWVG3690",
    EVENT_REMINDER_5MINS_BEFORE: "ZRHXV1QC2JM59ZK7J095JBFP1KR3",
}
