exclude: "^$"
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-ast
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/python/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/prettier/prettier
    rev: "2.0.4"
    hooks:
      - id: prettier
